# Generated by Django 5.1.1 on 2025-03-11 09:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=255)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('cognome', models.CharField(blank=True, max_length=255, null=True)),
                ('cellulare', models.CharField(blank=True, max_length=50, null=True)),
                ('indirizzo', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('societa', models.BooleanField(default=False)),
                ('piva', models.CharField(blank=True, max_length=50, null=True)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contatti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('n_dipendenti', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('sito', models.URLField(blank=True, null=True)),
                ('creato', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('partita_iva', models.CharField(blank=True, max_length=20, null=True)),
                ('specialita', models.TextField(blank=True, null=True)),
                ('citta', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('cronologia', models.TextField(blank=True, null=True)),
                ('recensioni', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Riferimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cognome', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=100, null=True)),
                ('cognome', models.CharField(max_length=100, null=True)),
                ('attivita', models.CharField(max_length=255, null=True)),
                ('cellulari', models.CharField(max_length=255, null=True)),
                ('numero_dipendenti', models.CharField(max_length=50, null=True)),
                ('sito_web', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('partita_iva', models.CharField(max_length=50, null=True)),
                ('specialita', models.TextField(null=True)),
                ('luogo', models.CharField(max_length=255, null=True)),
                ('note', models.TextField(null=True)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, null=True)),
                ('affidabilita', models.FloatField(blank=True, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornitori', to='gestione.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Lavoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.TextField()),
                ('fase', models.CharField(max_length=100)),
                ('importo', models.FloatField(default=0.0)),
                ('data_creazione', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField()),
                ('position', models.IntegerField(default=0)),
                ('selezionato', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lavori', to='gestione.cliente')),
                ('riferimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestione.riferimento')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('attachment', models.CharField(blank=True, max_length=255, null=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gestione.lavoro')),
            ],
        ),
        migrations.CreateModel(
            name='LavoroFornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confermato', models.BooleanField(default=False)),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.fornitore')),
                ('lavoro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lavoro_fornitori', to='gestione.lavoro')),
            ],
        ),
    ]
