# Generated by Django 5.1.1 on 2025-03-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lavoro',
            name='selezionato',
        ),
        migrations.AddField(
            model_name='lavoro',
            name='isSelezionato',
            field=models.BooleanField(default=False),
        ),
    ]
