# Generated by Django 5.1.1 on 2025-03-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0002_remove_lavoro_selezionato_lavoro_isselezionato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lavoro',
            old_name='isSelezionato',
            new_name='selezionato',
        ),
    ]
