# Generated by Django 5.1.1 on 2025-03-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0003_rename_isselezionato_lavoro_selezionato'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
