# Generated by Django 5.1.2 on 2025-07-04 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0004_emailaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronologiaModifiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ticket', 'Ticket'), ('column', 'Colonna'), ('client', 'Cliente'), ('supplier', 'Fornitore'), ('reference', 'Riferimento'), ('work', 'Lavoro')], max_length=20)),
                ('azione', models.CharField(choices=[('create', 'Creazione'), ('update', 'Modifica'), ('delete', 'Eliminazione'), ('move', 'Spostamento'), ('rename', 'Rinomina'), ('add', 'Aggiunta'), ('remove', 'Rimozione')], max_length=20)),
                ('dettagli', models.TextField()),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Cronologia Modifica',
                'verbose_name_plural': 'Cronologia Modifiche',
                'ordering': ['-timestamp'],
            },
        ),
    ]
