from django.urls import path
from . import views
from .views import login_view, logout_view

urlpatterns = [
    path('', views.index, name='index'),
    path('upload/', views.serve_uploaded_file_query, name='serve_uploaded_file_query'),
    path('upload_attachment/', views.upload_attachment, name='upload_attachment'),
    path('get_work_stages/', views.get_work_stages, name='get_work_stages'),
    path('get_clients/', views.get_clients, name='get_clients'),
    path('get_suppliers/', views.get_suppliers, name='get_suppliers'),
    path('add_work/', views.add_work, name='add_work'),
    path('update_work/', views.update_work, name='update_work'),
    path('update_work_stage/', views.update_work_stage, name='update_work_stage'),  
    path('get_comments/', views.get_comments, name='get_comments'),
    path('add_comment/', views.add_comment, name='add_comment'),
    path('delete_comment/', views.delete_comment, name='delete_comment'),
    path('delete_work/', views.delete_work, name='delete_work'),
    path('strumentiAI', views.strumenti_ai_view, name='strumentiAI'),
    path('fornitori', views.fornitori_view, name='fornitori'),
    path('clienti', views.clienti_view, name='clienti'),
    path('api/fornitori', views.lista_contatti, name='lista_fornitori'),
    path('api/clienti', views.lista_clienti, name='lista_clienti'),
    path('api/create-ticket', views.create_ticket, name='create_ticket'),
    path('crea-ticket-if', views.create_ticket_if, name='creaticket-if'),
    path('update_work_iframe/<int:work_id>/', views.update_work_iframe, name='update_work_iframe'),
    path('get_work/<int:work_id>/', views.get_work, name='get_work'),
    path('aggiungi_cliente', views.aggiungi_cliente, name='aggiungi_cliente'),
    path('aggiungi_fornitore/', views.aggiungi_fornitore, name='aggiungi_fornitore'),
    path('api/add_cliente/', views.add_cliente, name='add_cliente'),
    path('api/add_fornitore/', views.add_fornitore, name='add_fornitore'),
    path('cliente/<int:id>/', views.get_client_details, name='get_client_details'),
    path('fornitore/<int:id>/', views.get_fornitore_details, name='get_fornitore_details'),
    path('api/categorie/', views.list_categorie, name='list_categorie'),
    path('api/add_categoria/', views.add_categoria, name='add_categoria'),
    path('api/add_riferimento/', views.add_riferimento, name='add_riferimento'),
    path('api/get_riferimenti/', views.get_riferimenti, name='get_riferimenti'),
    path('riferimento/<int:id>/', views.get_riferimento_details, name='get_riferimento_details'),
    path('update_riferimento/<int:id>/', views.update_riferimento, name='update_riferimento'),
    path('update_fornitore/<int:id>/', views.update_fornitore, name='update_fornitore'),
    path('delete_fornitore/<int:id>/', views.delete_fornitore, name='delete_fornitore'),
    path('update_fornitore_iframe/<int:id>/', views.update_fornitore_iframe, name='update_fornitore_iframe'),
    path('update_cliente/<int:id>/', views.update_cliente, name='update_cliente'),
    path('delete_cliente/<int:id>/', views.delete_cliente, name='delete_cliente'),
    path('update_cliente_iframe/<int:id>/', views.update_cliente_iframe, name='update_cliente_iframe'),
    path('consiglia_fornitori/', views.consiglia_fornitori_iframe, name='consiglia_fornitori_iframe'),
    path('api/consiglia_fornitori/', views.consiglia_fornitori, name='consiglia_fornitori'),
    path('aggiungi_fornitori/', views.aggiungi_fornitori_iframe, name='aggiungi_fornitori_iframe'),
    path('api/aggiungi_fornitori/', views.aggiungi_fornitori, name='aggiungi_fornitori'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('api/send_email/', views.send_email, name='send_email'),
    path('api/get_saved_emails/', views.get_saved_emails, name='get_saved_emails'),
    path('api/get_stage_names/', views.get_stage_names, name='get_stage_names'),
    path('api/update_stage_name/', views.update_stage_name, name='update_stage_name'),
    # Endpoint di compatibilità (wrapper per le versioni avanzate)
    path('api/work/<int:work_id>/whatsapp-contacts/', views.get_whatsapp_contacts, name='get_whatsapp_contacts'),
    path('api/work/<int:work_id>/email-contacts/', views.get_email_contacts, name='get_email_contacts'),
    path('api/cronologia/', views.get_cronologia, name='get_cronologia'),
    path('api/work/<int:work_id>/whatsapp-contacts-advanced/', views.get_whatsapp_contacts_advanced, name='get_whatsapp_contacts_advanced'),
    path('api/work/<int:work_id>/email-contacts-advanced/', views.get_email_contacts_advanced, name='get_email_contacts_advanced'),
    # Nuovi endpoint per contatti solo del ticket
    path('api/work/<int:work_id>/whatsapp-contacts-ticket/', views.get_whatsapp_contacts_ticket_only, name='get_whatsapp_contacts_ticket_only'),
    path('api/work/<int:work_id>/email-contacts-ticket/', views.get_email_contacts_ticket_only, name='get_email_contacts_ticket_only'),
]

